### ISSUE TITLE
utilities::type<T>() doesn't work on MSVC

### ISSUE THREAD

**Issue by jbatnozic** [nessan/utilities#1]
Hi, I saw your library on reddit and I gave it a glance and saw an error.

Your implementation of `utilities::type<T>()` for MSVC should say

```cpp
std::string_view m_prefix  = "auto __cdecl utilities::type<";
```

in order to work properly.

Kind regards

**Comment by nessan** [comment]
Thanks Jovan!On Aug 27, 2024, at 8:39 PM, Jovan Batnožić ***@***.***> wrote:﻿
Hi, I saw your library on reddit and I gave it a glance and saw an error.
Your implementation of utilities::type<T>() for MSVC should say
std::string_view m_prefix  = "auto __cdecl utilities::type<";
in order to work properly.
Kind regards
